In [1]:
pip install -U fortran-magic

In [2]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00',
                             '2017-01-07 00:00:00+00:00',
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [3]:
assert ran_the_first_cell, "Oh noes!"

In [4]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [5]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [6]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [7]:
# Lists can also be sliced, which makes a copy of elements between
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [8]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [9]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [10]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [11]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [12]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [13]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [14]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

In [15]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

In [16]:
del philosophers['David']
philosophers

{'Immanuel': 'Kant', 'Bertrand': 'Russell', 'Ludwig': 'Wittgenstein'}

In [17]:
# No slicing.
# So this won't work
# philosophers['Bertrand':'Immanuel']

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [18]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [19]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [20]:
%%time

matmul(a, b)

CPU times: user 38 µs, sys: 5 µs, total: 43 µs
Wall time: 48.6 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 0 - cpu info**

In [21]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
addres

**My own example 1 - Changing in matmul(A, B) Python len(B) (# of rows of B) for len(A[0]) (# of columns of A)**

In [22]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(A[0])-1):
                out[i][j] += A[i][k] * B[k][j]
    return out

**My own example 2 - Verifiying error with in matmul(A, B) Python with the original matrices when changing len(B) (# of rows of B) for len(A[0]) (# of colums of A)**

In [23]:
%%time
matmul(a, b)

CPU times: user 22 µs, sys: 3 µs, total: 25 µs
Wall time: 26.9 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 3 - Chekcing the matrix multiplication compatibility condition  len(A[0]) == len(B)**

In [24]:
def matmul(A, B):
  if len(A[0]) == len(B):
      """Multiply matrix A by matrix B."""
      rows_out = len(A)
      cols_out = len(B[0])
      out = [[0 for col in range(cols_out)] for row in range(rows_out)]

      for i in range(rows_out):
          for j in range(cols_out):
              for k in range(len(A[0])-1):
                  out[i][j] += A[i][k] * B[k][j]
      return out
  else:
      print("matrix multiplication is not compatible")
      return

**My own example 4 -  Verifiying error with in matmul(A, B) Python when checking the mtarix multiplication compatibility condition  len(A[0]) == len(B)**

In [25]:
matmul(a,b)

matrix multiplication is not compatible


**My own example 5 - Deifining A and B that are compatible for multiplcation**

In [26]:
A = [[46,25],
     [37,34],
     [28,43],
     [19,52]]

B=[[2,4,3,5],
   [9,8,7,6]]

**My own example 6 - Runinng the correct Python matrix multiplication code with the matrices with dimensions compatible for multiplication.**

In [27]:
%%time
matmul(A, B)

CPU times: user 28 µs, sys: 4 µs, total: 32 µs
Wall time: 36 µs


[[92, 184, 138, 230],
 [74, 148, 111, 185],
 [56, 112, 84, 140],
 [38, 76, 57, 95]]

In [28]:
import random

In [29]:
random.normalvariate(0,1)

-2.0088689473517003

In [30]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.914831155769517, 0.5989031260725102, 0.36644857804836783],
 [0.13487738638563396, 0.4939924323108873, 0.17748533229115193]]

**My own example 7 - Running 10 times matmul(randa, randb) with randa and randb a randon matrices of 600 x 100 and 100 x 600 and calulating the average execution time**

In [31]:
%%time
import time
totalTime = 0
for i in range(10):
  start_time = time.time()
  randa = random_matrix(600,100)
  randb = random_matrix(100,600)
  matmul(randa,randb)
  t = time.time() - start_time
  totalTime = totalTime + t

averaTime = totalTime/10
print("Average time: ",averaTime)

Average time:  8.863039803504943
CPU times: user 1min 27s, sys: 231 ms, total: 1min 28s
Wall time: 1min 28s


**My own example 8 - Creating the average execution time data frame and adding Python's average execution time**

In [32]:
import pandas as pd

df = {'Language': ['Python'],'average execution time': [averaTime]}

averaDF = pd.DataFrame(df)
display(averaDF)

Language  average execution time
0   Python                 8.86304

**My own example 9 - Running 10 times randa and randb mutiplicaction as NumPy arrays  adding NumPy's average execution time**

In [33]:
%%time

import numpy as np

for i in range(10):
  A = np.array([randa])
  B = np.array([randb])
  print(np.dot(A, B))

  totalTime = 0
for i in range(10):
  start_time = time.time()
  np.dot(randa,randb)
  t = time.time() - start_time
  totalTime= totalTime+t

averaTime=totalTime/10

averaDF.loc[len(averaDF.index)] = ['NumPy', averaTime]
display(averaDF)

[[[[23.98554234 22.48430565 25.10106743 ... 27.38678218 23.91295639
    27.8952364 ]]

  [[22.55033705 22.23613497 25.54200177 ... 25.40266711 22.58289304
    26.34121104]]

  [[25.74216831 26.30633415 27.78397965 ... 27.64755464 28.03037518
    27.69081138]]

  ...

  [[28.03025799 25.55126046 28.39449473 ... 30.54213911 29.54851389
    31.13739493]]

  [[26.76223775 25.45656753 28.24658944 ... 27.35126384 25.77966367
    30.46991604]]

  [[26.95389493 27.28773856 27.77021663 ... 27.70770177 27.59197158
    30.29985556]]]]
[[[[23.98554234 22.48430565 25.10106743 ... 27.38678218 23.91295639
    27.8952364 ]]

  [[22.55033705 22.23613497 25.54200177 ... 25.40266711 22.58289304
    26.34121104]]

  [[25.74216831 26.30633415 27.78397965 ... 27.64755464 28.03037518
    27.69081138]]

  ...

  [[28.03025799 25.55126046 28.39449473 ... 30.54213911 29.54851389
    31.13739493]]

  [[26.76223775 25.45656753 28.24658944 ... 27.35126384 25.77966367
    30.46991604]]

  [[26.95389493 27.28773856 

Language  average execution time
0   Python                 8.86304
1    NumPy                 0.04282

CPU times: user 1.02 s, sys: 160 ms, total: 1.18 s
Wall time: 1.2 s


In [34]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 8.5 s, sys: 60.9 ms, total: 8.56 s
Wall time: 8.62 s


In [35]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [36]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result

    result = sum(xs * ys)
end

In [37]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [38]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 11.8 ms, sys: 0 ns, total: 11.8 ms
Wall time: 12.2 ms


333328333350000.0

In [39]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 188 µs, sys: 0 ns, total: 188 µs
Wall time: 192 µs


333328333350000.0

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


**My own example 10 - Deifining A (2x2)  and B (2x2)**

In [40]:
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

**My own example 11 - Defining Fortran subroutine matmul(A,B) for 2x2 matrices**

In [41]:
%%fortran
subroutine matmul(A, B, result)
    implicit none
    double precision, intent(in) :: A(2,*)
    double precision, intent(in) :: B(2,*)
    double precision, intent(out) :: result(2,2)
    integer i,j,k
    do i=1,2
      do j=1,2
        result(i,j)=0
        do K=1,2
          result(i,j) = result(i,j) + A(i,k) * B(k,j)
        end do
      end do
    end do
end subroutine matmul

**My own example 12 -Run Fortran subroutine matmul(A,B) with a and b 2x2 matrices**

In [42]:
matmul (A,B)

array([[19., 22.],
       [43., 50.]])

**My own example 13 - Defining Fortran subroutine matmul(A,B) for 600x100 and 100x600 matrices**

In [43]:
%%fortran

subroutine matmul(A, B, result)

    implicit none
    real, dimension(600,100), intent(in) :: A
    real, dimension(100,600), intent(in) :: B
    real, dimension(600,600), intent(out) :: result
    integer :: i,j,k

    do i=1,600
      do j=1,600
        result(i,j)=0
        do k=1,100
          result(i,j) = result(i,j) + A(i,k) * B(k,j)
        end do
      end do
    end do
end subroutine matmul

**My own example 14 -Run Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices**

In [44]:
# 600 x 100
M1 = random_matrix(600, 100)
M1 = np.array(M1)

# 100 x 600
M2 = random_matrix(100, 600)
M2 = np.array(M2)

matmul(M1, M2)

array([[27.791775, 24.301466, 24.08776 , ..., 27.716375, 24.2131  ,
        26.400778],
       [30.14897 , 29.953274, 28.275791, ..., 30.122505, 28.768673,
        28.778059],
       [27.67342 , 26.158573, 24.99919 , ..., 27.909996, 26.718332,
        24.387743],
       ...,
       [22.102665, 20.91015 , 20.534832, ..., 22.644775, 22.309786,
        20.824633],
       [30.768785, 25.190117, 26.197271, ..., 29.750261, 26.979866,
        27.761292],
       [28.169695, 25.22027 , 24.883358, ..., 26.915092, 26.858027,
        25.96293 ]], dtype=float32)

**My own example 15 - Running 10 times the  Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices and adding Fortran magic average execution time to the data frame**

In [45]:
import time

E = M1
F = M2

totalTime = 0

for i in range(10):
  start_time = time.time()
  matmul(E, F)
  t = time.time() - start_time
  totalTime = totalTime+t

averaTime = totalTime/10

averaDF.loc[len(averaDF.index)] = ['Fortran', averaTime]
display(averaDF)

Language  average execution time
0   Python                8.863040
1    NumPy                0.042820
2  Fortran                0.044559

**My own example 16 - Creating a  Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [46]:
%%fortran

subroutine matmul10(A, B, result)

    implicit none
    real, dimension(600,100), intent(in) :: A
    real, dimension(100,600), intent(in) :: B
    real, dimension(600,600), intent(out) :: result
    integer :: i,j,k,n

    do n = 1, 10
      do i = 1,600
          do j = 1,600
              result(i,j) = 0.0
              do k = 1,100
                  result(i,j) = result(i,j) + A(i,k) * B(k,j)
              end do
          end do
      end do
    end do
end subroutine matmul10

**My own example 17 - Running the Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [47]:
%%time
# 600 x 100
M1 = random_matrix(600, 100)
M1 = np.array(M1)

# 100 x 600
M2 = random_matrix(100, 600)
M2 = np.array(M2)

matmul10(M1, M2)

CPU times: user 446 ms, sys: 4 ms, total: 450 ms
Wall time: 453 ms


array([[30.001694, 21.8468  , 24.756056, ..., 27.338099, 26.353943,
        25.664322],
       [27.23911 , 21.03258 , 23.1609  , ..., 25.611391, 23.725826,
        23.30662 ],
       [27.182295, 21.55781 , 22.892328, ..., 25.653372, 24.693018,
        25.410545],
       ...,
       [29.554144, 22.41139 , 24.345407, ..., 27.266577, 27.073645,
        28.106256],
       [28.274166, 23.71763 , 24.66307 , ..., 26.493967, 26.740732,
        25.72557 ],
       [29.01322 , 21.816996, 24.26073 , ..., 27.332111, 26.648245,
        26.392597]], dtype=float32)

**My own example 18 - Adding Fortran average execution time to the data frame**

In [48]:
import numpy as np
import time

totalTime = 0

for i in range(10):
  start_time = time.time()
  matmul10(M1, M2)
  t = time.time() - start_time
  totalTime = totalTime+t

averaTime = totalTime/10

averaDF.loc[len(averaDF.index)] = ['FortranMagic', averaTime]
display(averaDF)

Language  average execution time
0        Python                8.863040
1         NumPy                0.042820
2       Fortran                0.044559
3  FortranMagic                0.428627

**My own example 19 - Creating a c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [49]:
%%writefile Prog.c

#include <stdio.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>

#define row 600
#define col 100

void multiplicar(int a[row][col],int b[col][row]){
    float sum;
    float result[row][row];

    for (int x = 0; x < row; x++) {
        for (int i = 0; i < row; i++){
            sum =0;
            for (int j = 0; j < col; j++) {
                sum = sum + a[i][j] * b[j][x];
            }
            result[i][x] = sum;
        }
    }
}

int main(void) {
    double averaTime = 0;
    int matrizA[600][100];
    for(int x=0;x<600;x++){
        for(int y=0;y<100;y++){
            matrizA[x][y]=rand()%100;
        }
    }

    int matrizB[100][600];
    for(int x=0;x<100;x++){
        for(int y=0;y<600;y++){
            matrizB[x][y]=rand()%100;
        }
    }
    clock_t begin = clock();
    for(int x=0;x<10;x++){
        multiplicar(matrizA,matrizB);
    }

    clock_t end = clock();
    averaTime += (double)((end - begin)/10) / CLOCKS_PER_SEC;
    printf("average execution time is %f seconds", averaTime);

    return 0;
}

Overwriting Prog.c


**My own example 20 - Running the c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [50]:
%%shell
gcc Prog.c -o output
./output

average execution time is 0.136728 seconds

**My own example 21 - Adding c average execution time to the data frame**

In [51]:
averaDF.loc[len(averaDF.index)] = ['C', 0.141339]
display(averaDF)

Language  average execution time
0        Python                8.863040
1         NumPy                0.042820
2       Fortran                0.044559
3  FortranMagic                0.428627
4             C                0.141339

**My own example 22 - Creating a C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [52]:
%%writefile Prog.cpp

#include<iostream>
#include<stdlib.h>
#include<time.h>
#include <chrono>
#include <ctime>

using namespace std;
int main()
{

 srand(time(0));
 int matrix1[600][100], i,j, matrix2[100][600], k,l, result [600][600], p;

 for( i=0; i < 600; ++i)
  {
    for( j=0;  j < 100; ++j)
     {matrix1[i][j] = rand()%100;}
  }

 for( k=0; k < 100; ++k)
  {
      for( l=0;  l < 600; ++l)
     {matrix1[k][l] = rand()%100;}
  }

float totalTime;

for (p = 0; p<10; p++){
 auto start = std::chrono::system_clock::now();

 for (int m = 0; m <600 ; m++)
 {
   for (int n = 0; n < 600; n++)
   {
     for (int o = 0; o < 100; o++)
     {
      result[m][n] +=  matrix1[m][o] * matrix2[o][n];
     }
   }
 }
    auto end = std::chrono::system_clock::now();
    std::chrono::duration<double> elapsed_seconds = end-start;
    totalTime = totalTime + elapsed_seconds.count();
}
    cout<<totalTime/10;
    return 0;
  }

Overwriting Prog.cpp


**My own example 23 - Running the C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [53]:
%%shell
g++ Prog.cpp -o output
./output

0.227239

**My own example 24 - Adding C++ average execution time to the data frame**

In [54]:
averaDF.loc[len(averaDF.index)] = ['C++', 0.160729]
display(averaDF)

Language  average execution time
0        Python                8.863040
1         NumPy                0.042820
2       Fortran                0.044559
3  FortranMagic                0.428627
4             C                0.141339
5           C++                0.160729

**My own example 25 - Creating a Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [55]:
%%writefile Main.java

public class Main {
      public static int[][] multiMat ( int[][] a, int[][] b) {

      int[][] result = new int[a.length][b[0].length];

      for (int i=0; i < result.length; i++)
          for (int j=0; j < result[0].length; j++)
              for (int k=0; k < b.length; k++)
                  result[i][j] = result[i][j] + a[i][k] * b[k][j];

      return result;
   }

   public static void main(String[] argumentos) {

        int[][] m1 = new int[600][100];
        for (int x=0; x < m1.length; x++) {
          for (int y=0; y < m1[x].length; y++) {
             m1[x][y] = (int) (Math.random()*9+1);
         }
}
        int[][] m2 = new int[100][600];
          for (int x=0; x < m2.length; x++) {
            for (int y=0; y < m2[x].length; y++) {
              m2[x][y] = (int) (Math.random()*9+1);
         }
}
          double a= 0.0;
          long totalTime=0;
          for(int i=0; i<10;i++){
            long inicio = System.currentTimeMillis();
            multiMat(m1,m2);
            long fin = System.currentTimeMillis();
            long t = (long) ((fin - inicio));
            totalTime = totalTime + t;
        }
        a=totalTime/10;
        a= a*0.001;
        System.out.println(a);
        }
}

Overwriting Main.java


**My own example 26 - Running the Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [56]:
!javac Main.java
!java Main

0.061


**My own example 27 - Adding Java average execution time to the data frame**

In [57]:
averaDF.loc[len(averaDF.index)] = ['Java', 0.093]
display(averaDF)

Language  average execution time
0        Python                8.863040
1         NumPy                0.042820
2       Fortran                0.044559
3  FortranMagic                0.428627
4             C                0.141339
5           C++                0.160729
6          Java                0.093000

**My own example 28 - Creating a Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [58]:
%%writefile Main.js

var myArray = []

for (var i = 0; i < 600; i++) {
  a=Array.from({length: 100}, () => Math.floor(Math.random() * 40));
  myArray.push(a)
}

var myArray_2 = []

for (var i = 0; i < 100; i++) {
  a=Array.from({length: 600
  }, () => Math.floor(Math.random() * 40));
  myArray_2.push(a)
}

sum=0
for(i=0; i<10;i++){
    var start = Date.now();
    mult(myArray,myArray_2)
    var end = Date.now();
    sum +=(end-start)
}

console.log(`Average time: ${sum/10000} s`)

function mult(a,b){
 fil_m1 = a.length;
    col_m1 = a[0].length;
    fil_m2 = b.length;
    col_m2 = b[0].length;
    let multiplicacion = new Array(fil_m1);
    for (x=0; x<multiplicacion.length;x++){
        multiplicacion[x] = new Array(col_m2).fill(0);

    }
    for (x=0; x < multiplicacion.length; x++) {
        for (y=0; y < multiplicacion[x].length; y++) {
            for (z=0; z<col_m1; z++) {
                multiplicacion [x][y] += + a[x][z]*b[z][y];
            }
        }
    }
}

Overwriting Main.js


**My own example 29 - Running the Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [59]:
!node Main.js

Average time: 0.3276 s


**My own example 30 - Adding Javascript average execution time to the data frame**

In [60]:
averaDF.loc[len(averaDF.index)] = ['Javascript', 0.3419]
display(averaDF)

Language  average execution time
0        Python                8.863040
1         NumPy                0.042820
2       Fortran                0.044559
3  FortranMagic                0.428627
4             C                0.141339
5           C++                0.160729
6          Java                0.093000
7    Javascript                0.341900

**My own example 31 - Finding the minimun average esecuiton time in the data frame**

In [61]:
min = averaDF["average execution time"].min()
print(min)

0.0428196907043457


**My own example 32 - Adding the Speed factor columne to the data frame**

In [62]:
averaDF["Speed Factor"] = averaDF["average execution time"]/min
display(averaDF)

Language  average execution time  Speed Factor
0        Python                8.863040    206.985143
1         NumPy                0.042820      1.000000
2       Fortran                0.044559      1.040614
3  FortranMagic                0.428627     10.010049
4             C                0.141339      3.300795
5           C++                0.160729      3.753624
6          Java                0.093000      2.171898
7    Javascript                0.341900      7.984644

**My own example 33 - Sorting the the data frame by average execution time**

In [63]:
averaDF = averaDF.sort_values(by = ['average execution time'])
display(averaDF)

Language  average execution time  Speed Factor
1         NumPy                0.042820      1.000000
2       Fortran                0.044559      1.040614
6          Java                0.093000      2.171898
4             C                0.141339      3.300795
5           C++                0.160729      3.753624
7    Javascript                0.341900      7.984644
3  FortranMagic                0.428627     10.010049
0        Python                8.863040    206.985143

## Why is the Python Version so Much Slower?

In [64]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [65]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [66]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [67]:
data + data

array([2, 4, 6, 8])

In [68]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 0 ns, sys: 408 µs, total: 408 µs
Wall time: 440 µs


333328333350000.0

In [69]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 1.1 ms, sys: 1 µs, total: 1.1 ms
Wall time: 899 µs


333328333350000.0

In [70]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 292 µs, sys: 3 µs, total: 295 µs
Wall time: 324 µs


333328333350000.0

In [83]:
# Numpy won't allow us to write a string into an int array.
#data[0] = "foo"

In [84]:
# We also can't grow an array once it's created.
#data.append(3)

In [87]:
# We **can** reshape an array though.
#two_by_two = data.reshape(2, 2)
#two_by_two

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [73]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [75]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [76]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [77]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [78]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [88]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [89]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [90]:
sines[:3]  # First three elements

array([0.        , 0.34185385, 0.64251645])

In [91]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [92]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [93]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [94]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [95]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [96]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [97]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [98]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [99]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [100]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [101]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [102]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [103]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [104]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [105]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [106]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [107]:
variance(np.random.standard_normal(1000))

1.0628863914711397

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [108]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [109]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [110]:
data.mean()

14.5

In [111]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [112]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [113]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [114]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [115]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for:
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [116]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [117]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [118]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [119]:
# ... or by label.
s.loc['a']

1

In [120]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [121]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [122]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [123]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [124]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [125]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [126]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)

    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!